### ISSUE TITLE
为什么执行npm run build 后图片引用路径不对了

### ISSUE THREAD

**Issue by lilu1814** [CRONWMMM/multi_page_app_template#1]
![image](https://user-images.githubusercontent.com/16162077/56353173-6d519d80-6203-11e9-9d57-df4d3154de26.png)

**Comment by lilu1814** [comment]
模板里修改页面上没有热更新
![image](https://user-images.githubusercontent.com/16162077/56353677-80b13880-6204-11e9-92db-aeb88a0b5321.png)

**Comment by CRONWMMM** [comment]
@lilu1814 打包完成后，图片引用路径问题已修复~
模板修改页面没有热更新的问题，我查看了很多文档，说是 webpack 原生不支持 html 的热更新，因为 webpack 并不把视图文件视为一个 bundle ，这个问题我会继续尝试，看看有没有好的解决方式。

**Comment by CRONWMMM** [comment]
@lilu1814 新增了支持模板文件热更新的代码
