### ISSUE TITLE
关于这个框架的几个疑惑

### ISSUE THREAD

**Issue by NameWjp** [CRONWMMM/multi_page_app_template#2]
1. 关于设置环境变量，第一个命令产生的环境变量是process.env.NODE_ENV='production'，应该就不需要后面的--env这个命令了吧。而且webpack设置环境变量需要一个函数去接受，这里好像并没有用。
![image](https://user-images.githubusercontent.com/32758131/56939110-fc7e7f80-6b38-11e9-9b37-4e43602b3b8e.png)

2. dev模式下没有配置optimization，所以这里是不是区分一下模式?
![image](https://user-images.githubusercontent.com/32758131/56942917-b2ed5f00-6b4f-11e9-80d5-c361e24394e6.png)

3.  这两个配置项有用么。。我再github上找不到，去掉之后也没有影响。
![image](https://user-images.githubusercontent.com/32758131/56945227-ff896800-6b58-11e9-86d8-d68346558494.png)

4.这两个问题如何解决？
![image](https://user-images.githubusercontent.com/32758131/56945851-1204a100-6b5b-11e9-93e9-72cbb1beb3f4.png)

**Comment by CRONWMMM** [comment]
@NameWjp 你好，我看了下你说的几个问题，确实存在，谢谢指正~
1. 这里的 --env 确实没有必要，可以删掉
2. 这块需要判断一下模式，生产环境下才需要分 manifest 和 vendors
3. webpack-dev-middleware 的一些配置项不同于 webpack-dev-server ，我没有仔细看文档，把 webpack-dev-server 的一部分配置写进来了，hot 和 overlay 在 webpack-dev-middleware 里是没有的，可以去掉
4. 这两个问题，可以在 document.body 内容替换之前，将事件手动解绑。
