### ISSUE TITLE
ejs怎么打包成html?

### ISSUE THREAD

**Issue by hlq96958** [CRONWMMM/multi_page_app_template#3]
打包后的views目录中是ejs文件，请问怎么打包成html文件呢？

**Comment by CRONWMMM** [comment]
你好，这个功能可以看我最近的提交记录：
[支持 ejs 文件转成 html 格式文件](https://github.com/CRONWMMM/multi_page_app_template/commit/1c62620df11c73bce7ca0ea6db041866b4f36bcc)
