### ISSUE TITLE
项目是否可以使用ant design 作为样式组件

### ISSUE THREAD

**Issue by yangzhiganluk** [CRONWMMM/multi_page_app_template#4]
如果可以使用 请问是像像框架那样安装依赖那样安装吗

**Comment by CRONWMMM** [comment]
你好，这个 Demo可以用来搭建考虑 SEO 的、交互简单的官网，并不适合开发单页应用。如果需要使用 ant design 的话，还是建议使用 webpack 构建 react 应用的方式。
